<?php

namespace Semantikos\ClientBundle\Repository;

/**
 * RefSetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefSetRepository extends \Doctrine\ORM\EntityRepository
{
}
