<?php

namespace Semantikos\ClientBundle\API;


 function autoload_69189a250467c5908f7d5e5483132f4d($class)
{
    $classes = array(
        'ServicioDeBusqueda' => __DIR__ .'/ServicioDeBusqueda.php',
        'getCrossmapSets' => __DIR__ .'/getCrossmapSets.php',
        'getCrossmapSetsResponse' => __DIR__ .'/getCrossmapSetsResponse.php',
        'CrossmapSetsResponse' => __DIR__ .'/CrossmapSetsResponse.php',
        'crossmapSets' => __DIR__ .'/crossmapSets.php',
        'CrossmapSet' => __DIR__ .'/CrossmapSet.php',
        'crossmapSetMembersDeCrossmapSet' => __DIR__ .'/crossmapSetMembersDeCrossmapSet.php',
        'crossmapSetMembersDeCrossmapSetResponse' => __DIR__ .'/crossmapSetMembersDeCrossmapSetResponse.php',
        'CrossmapSetMembersResponse' => __DIR__ .'/CrossmapSetMembersResponse.php',
        'crossmapSetMembers' => __DIR__ .'/crossmapSetMembers.php',
        'CrossmapSetMember' => __DIR__ .'/CrossmapSetMember.php',
        'conceptoPorIdDescripcion' => __DIR__ .'/conceptoPorIdDescripcion.php',
        'conceptoPorIdDescripcionResponse' => __DIR__ .'/conceptoPorIdDescripcionResponse.php',
        'Concepto' => __DIR__ .'/Concepto.php',
        'refSets' => __DIR__ .'/refSets.php',
        'descripciones' => __DIR__ .'/descripciones.php',
        'atributos' => __DIR__ .'/atributos.php',
        'relaciones' => __DIR__ .'/relaciones.php',
        'relacionesSnomedCT' => __DIR__ .'/relacionesSnomedCT.php',
        'crossmapsIndirectos' => __DIR__ .'/crossmapsIndirectos.php',
        'crossmapsDirectos' => __DIR__ .'/crossmapsDirectos.php',
        'Categoria' => __DIR__ .'/Categoria.php',
        'RefSet' => __DIR__ .'/RefSet.php',
        'conceptos' => __DIR__ .'/conceptos.php',
        'Descripcion' => __DIR__ .'/Descripcion.php',
        'Usuario' => __DIR__ .'/Usuario.php',
        'Atributo' => __DIR__ .'/Atributo.php',
        'Relacion' => __DIR__ .'/Relacion.php',
        'Objetivo' => __DIR__ .'/Objetivo.php',
        'fields' => __DIR__ .'/fields.php',
        'entry' => __DIR__ .'/entry.php',
        'TablaAuxiliar' => __DIR__ .'/TablaAuxiliar.php',
        'columnaTablaAuxiliar' => __DIR__ .'/columnaTablaAuxiliar.php',
        'ColumnaTablaAuxiliar' => __DIR__ .'/ColumnaTablaAuxiliar.php',
        'DefinicionRelacion' => __DIR__ .'/DefinicionRelacion.php',
        'definicionesAtributoRelacion' => __DIR__ .'/definicionesAtributoRelacion.php',
        'Multiplicidad' => __DIR__ .'/Multiplicidad.php',
        'DefinicionObjetivo' => __DIR__ .'/DefinicionObjetivo.php',
        'DefinicionRelacionAtributo' => __DIR__ .'/DefinicionRelacionAtributo.php',
        'AtributoRelacion' => __DIR__ .'/AtributoRelacion.php',
        'RelacionSnomedCT' => __DIR__ .'/RelacionSnomedCT.php',
        'IndirectCrossmap' => __DIR__ .'/IndirectCrossmap.php',
        'listaRefSet' => __DIR__ .'/listaRefSet.php',
        'listaRefSetResponse' => __DIR__ .'/listaRefSetResponse.php',
        'RespuestaRefSets' => __DIR__ .'/RespuestaRefSets.php',
        'refsets' => __DIR__ .'/refsets.php',
        'conceptosPorRefSet' => __DIR__ .'/conceptosPorRefSet.php',
        'PeticionConceptosPorRefSet' => __DIR__ .'/PeticionConceptosPorRefSet.php',
        'conceptosPorRefSetResponse' => __DIR__ .'/conceptosPorRefSetResponse.php',
        'RespuestaConceptosPorRefSet' => __DIR__ .'/RespuestaConceptosPorRefSet.php',
        'Paginacion' => __DIR__ .'/Paginacion.php',
        'ConceptoLight' => __DIR__ .'/ConceptoLight.php',
        'buscarTruncatePerfect' => __DIR__ .'/buscarTruncatePerfect.php',
        'PeticionBuscarTermino' => __DIR__ .'/PeticionBuscarTermino.php',
        'buscarTruncatePerfectResponse' => __DIR__ .'/buscarTruncatePerfectResponse.php',
        'RespuestaConceptosPorCategoria' => __DIR__ .'/RespuestaConceptosPorCategoria.php',
        'refSetsPorIdDescripcion' => __DIR__ .'/refSetsPorIdDescripcion.php',
        'PeticionRefSetsPorIdDescripcion' => __DIR__ .'/PeticionRefSetsPorIdDescripcion.php',
        'refSetsPorIdDescripcionResponse' => __DIR__ .'/refSetsPorIdDescripcionResponse.php',
        'listaCategorias' => __DIR__ .'/listaCategorias.php',
        'listaCategoriasResponse' => __DIR__ .'/listaCategoriasResponse.php',
        'crossMapsDirectosPorIDDescripcion' => __DIR__ .'/crossMapsDirectosPorIDDescripcion.php',
        'crossMapsDirectosPorIDDescripcionResponse' => __DIR__ .'/crossMapsDirectosPorIDDescripcionResponse.php',
        'conceptosPorCategoria' => __DIR__ .'/conceptosPorCategoria.php',
        'PeticionPorCategoria' => __DIR__ .'/PeticionPorCategoria.php',
        'conceptosPorCategoriaResponse' => __DIR__ .'/conceptosPorCategoriaResponse.php',
        'descripcionesPreferidasPorRefSet' => __DIR__ .'/descripcionesPreferidasPorRefSet.php',
        'descripcionesPreferidasPorRefSetResponse' => __DIR__ .'/descripcionesPreferidasPorRefSetResponse.php',
        'obtenerTerminosPedibles' => __DIR__ .'/obtenerTerminosPedibles.php',
        'PeticionConceptosPedibles' => __DIR__ .'/PeticionConceptosPedibles.php',
        'obtenerTerminosPediblesResponse' => __DIR__ .'/obtenerTerminosPediblesResponse.php',
        'RespuestaBuscarTermino' => __DIR__ .'/RespuestaBuscarTermino.php',
        'buscarTermino' => __DIR__ .'/buscarTermino.php',
        'PeticionBuscarTerminoSimple' => __DIR__ .'/PeticionBuscarTerminoSimple.php',
        'buscarTerminoResponse' => __DIR__ .'/buscarTerminoResponse.php',
        'RespuestaBuscarTerminoGenerica' => __DIR__ .'/RespuestaBuscarTerminoGenerica.php',
        'descripcionesPerfectMatch' => __DIR__ .'/descripcionesPerfectMatch.php',
        'descripcionesNoValidas' => __DIR__ .'/descripcionesNoValidas.php',
        'descripcionesPendientes' => __DIR__ .'/descripcionesPendientes.php',
        'DescripcionPerfectMatch' => __DIR__ .'/DescripcionPerfectMatch.php',
        'DescripcionNoValida' => __DIR__ .'/DescripcionNoValida.php',
        'descripcionesSugeridas' => __DIR__ .'/descripcionesSugeridas.php',
        'DescripcionPendiente' => __DIR__ .'/DescripcionPendiente.php',
        'DescripcionSimplificada' => __DIR__ .'/DescripcionSimplificada.php',
        'crossMapsIndirectosPorIDDescripcion' => __DIR__ .'/crossMapsIndirectosPorIDDescripcion.php',
        'crossMapsIndirectosPorIDDescripcionResponse' => __DIR__ .'/crossMapsIndirectosPorIDDescripcionResponse.php',
        'IndirectCrossmapsSearch' => __DIR__ .'/IndirectCrossmapsSearch.php',
        'indirectCrossmaps' => __DIR__ .'/indirectCrossmaps.php',
        'NotFoundFault' => __DIR__ .'/NotFoundFault.php',
        'IllegalInputFault' => __DIR__ .'/IllegalInputFault.php'
    );
    if (!empty($classes[$class])) {
        include $classes[$class];
    };
}

spl_autoload_register('autoload_69189a250467c5908f7d5e5483132f4d');

// Do nothing. The rest is just leftovers from the code generation.
{
}
