
package cl.minsal.semantikos.ws.shared;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "IllegalInputFault", targetNamespace = "http://service.ws.semantikos.minsal.cl/")
public class IllegalInputFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private IllegalInputFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public IllegalInputFault_Exception(String message, IllegalInputFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public IllegalInputFault_Exception(String message, IllegalInputFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: cl.minsal.semantikos.ws.shared.IllegalInputFault
     */
    public IllegalInputFault getFaultInfo() {
        return faultInfo;
    }

}
