
package cl.minsal.semantikos.ws.shared;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "NotFoundFault", targetNamespace = "http://service.ws.semantikos.minsal.cl/")
public class NotFoundFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NotFoundFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public NotFoundFault_Exception(String message, NotFoundFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public NotFoundFault_Exception(String message, NotFoundFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: cl.minsal.semantikos.ws.shared.NotFoundFault
     */
    public NotFoundFault getFaultInfo() {
        return faultInfo;
    }

}
