
package cl.minsal.semantikos.ws.shared;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicioDeBusqueda", targetNamespace = "http://service.ws.semantikos.minsal.cl/", wsdlLocation = "file:/home/des01c7/IdeaProjects/servidor-terminologico/SemantikosClientesWS/resources/ServicioDeBusqueda.wsdl")
public class ServicioDeBusqueda
    extends Service
{

    private final static URL SERVICIODEBUSQUEDA_WSDL_LOCATION;
    private final static WebServiceException SERVICIODEBUSQUEDA_EXCEPTION;
    private final static QName SERVICIODEBUSQUEDA_QNAME = new QName("http://service.ws.semantikos.minsal.cl/", "ServicioDeBusqueda");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/des01c7/IdeaProjects/servidor-terminologico/SemantikosClientesWS/resources/ServicioDeBusqueda.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIODEBUSQUEDA_WSDL_LOCATION = url;
        SERVICIODEBUSQUEDA_EXCEPTION = e;
    }

    public ServicioDeBusqueda() {
        super(__getWsdlLocation(), SERVICIODEBUSQUEDA_QNAME);
    }

    public ServicioDeBusqueda(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIODEBUSQUEDA_QNAME, features);
    }

    public ServicioDeBusqueda(URL wsdlLocation) {
        super(wsdlLocation, SERVICIODEBUSQUEDA_QNAME);
    }

    public ServicioDeBusqueda(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIODEBUSQUEDA_QNAME, features);
    }

    public ServicioDeBusqueda(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioDeBusqueda(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SearchService
     */
    @WebEndpoint(name = "SearchServicePort")
    public SearchService getSearchServicePort() {
        return super.getPort(new QName("http://service.ws.semantikos.minsal.cl/", "SearchServicePort"), SearchService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SearchService
     */
    @WebEndpoint(name = "SearchServicePort")
    public SearchService getSearchServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ws.semantikos.minsal.cl/", "SearchServicePort"), SearchService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIODEBUSQUEDA_EXCEPTION!= null) {
            throw SERVICIODEBUSQUEDA_EXCEPTION;
        }
        return SERVICIODEBUSQUEDA_WSDL_LOCATION;
    }

}
