
package cl.minsal.semantikos.ws.shared;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicioDeIngreso", targetNamespace = "http://service.ws.semantikos.minsal.cl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioDeIngreso {


    /**
     * 
     * @param peticionCodificacionDeNuevoTermino
     * @return
     *     returns cl.minsal.semantikos.ws.shared.RespuestaCodificacionDeNuevoTermino
     * @throws IllegalInputFault_Exception
     */
    @WebMethod
    @WebResult(name = "respuestaCodificacionDeNuevoTermino", targetNamespace = "http://service.ws.semantikos.minsal.cl/")
    @RequestWrapper(localName = "codificacionDeNuevoTermino", targetNamespace = "http://service.ws.semantikos.minsal.cl/", className = "cl.minsal.semantikos.ws.shared.CodificacionDeNuevoTermino")
    @ResponseWrapper(localName = "codificacionDeNuevoTerminoResponse", targetNamespace = "http://service.ws.semantikos.minsal.cl/", className = "cl.minsal.semantikos.ws.shared.CodificacionDeNuevoTerminoResponse")
    public RespuestaCodificacionDeNuevoTermino codificacionDeNuevoTermino(
        @WebParam(name = "peticionCodificacionDeNuevoTermino", targetNamespace = "http://service.ws.semantikos.minsal.cl/")
        PeticionCodificacionDeNuevoTermino peticionCodificacionDeNuevoTermino)
        throws IllegalInputFault_Exception
    ;

    /**
     * 
     * @param descriptionID
     * @return
     *     returns cl.minsal.semantikos.ws.shared.Descripcion
     */
    @WebMethod
    @WebResult(name = "descripcionCounter", targetNamespace = "")
    @RequestWrapper(localName = "incrementarContadorDescripcionConsumida", targetNamespace = "http://service.ws.semantikos.minsal.cl/", className = "cl.minsal.semantikos.ws.shared.IncrementarContadorDescripcionConsumida")
    @ResponseWrapper(localName = "incrementarContadorDescripcionConsumidaResponse", targetNamespace = "http://service.ws.semantikos.minsal.cl/", className = "cl.minsal.semantikos.ws.shared.IncrementarContadorDescripcionConsumidaResponse")
    public Descripcion incrementarContadorDescripcionConsumida(
        @WebParam(name = "descriptionID", targetNamespace = "")
        String descriptionID);

}
