

-- Function: semantikos.get_description_by_business_id(IN i character varying)

-- DROP FUNCTION semantikos.get_description_by_business_id(IN i character varying);

CREATE OR REPLACE FUNCTION semantikos.get_description_by_business_id(IN i character varying)
  RETURNS TABLE(id bigint, description_id character varying, id_description_type bigint, term character varying, case_sensitive boolean, autogenerated boolean, is_published boolean, validity_until timestamp without time zone, id_concept bigint, id_user bigint, creation_date timestamp without time zone, is_modeled boolean) AS
$BODY$
begin
  RETURN QUERY select d.id, d.descid ,d.id_description_type, d.term, d.case_sensitive, d.autogenerated_name,  d.is_published,d.validity_until, d.id_concept,d.id_user,d.creation_date,d.is_modeled
               from semantikos.smtk_description as d
                 join  semantikos.smtk_description_type as td
                   on d.id_description_type=td.id
               where d.descid = i;
END;
$BODY$
LANGUAGE plpgsql VOLATILE
COST 100
ROWS 1000;
ALTER FUNCTION semantikos.get_description_by_business_id(character varying)
OWNER TO postgres;

